# -*- coding: utf-8 -*-
"""my_module.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/ArashiNilou/754287f8ec97177fb06f7a3b3c90d04a/my_module.ipynb
"""

def caree(x):
  return x ** 2

def cube(x):
  return x ** 3

def factoriel(x):
  y = 1
  for i in range(x, 1, -1):
      y *= i
  return y

def absolu(x):
  x = abs(x)
  return x

def create_list():
  nombres = input("Saisissez les element de la list : ")
  ma_list = [int(x) for x in nombres.split()]
  return ma_list